baseurl: ""
url: ""

default_lang: en
languages:
  - code: en
    label: EN
    home: /
  - code: zh
    label: 中文
    home: /zh/

logo: "https://avatars.githubusercontent.com/u/157189119"
favicon: "https://avatars.githubusercontent.com/u/157189119"

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext
      lang: en
  - scope:
      path: "_pages/zh"
    values:
      lang: zh
      permalink: /zh/:basename:output_ext
  - scope:
      path: "index.html"
    values:
      lang: en
  - scope:
      path: "zh/index.html"
    values:
      lang: zh

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
